/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as AiReadinessRouteImport } from './routes/ai-readiness'
import { Route as IndexRouteImport } from './routes/index'

const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const AiReadinessRoute = AiReadinessRouteImport.update({
  id: '/ai-readiness',
  path: '/ai-readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-readiness': typeof AiReadinessRoute
  '/changelog': typeof ChangelogRoute
  '/compare': typeof CompareRoute
  '/learn': typeof LearnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-readiness': typeof AiReadinessRoute
  '/changelog': typeof ChangelogRoute
  '/compare': typeof CompareRoute
  '/learn': typeof LearnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-readiness': typeof AiReadinessRoute
  '/changelog': typeof ChangelogRoute
  '/compare': typeof CompareRoute
  '/learn': typeof LearnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ai-readiness' | '/changelog' | '/compare' | '/learn'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ai-readiness' | '/changelog' | '/compare' | '/learn'
  id: '__root__' | '/' | '/ai-readiness' | '/changelog' | '/compare' | '/learn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiReadinessRoute: typeof AiReadinessRoute
  ChangelogRoute: typeof ChangelogRoute
  CompareRoute: typeof CompareRoute
  LearnRoute: typeof LearnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-readiness': {
      id: '/ai-readiness'
      path: '/ai-readiness'
      fullPath: '/ai-readiness'
      preLoaderRoute: typeof AiReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiReadinessRoute: AiReadinessRoute,
  ChangelogRoute: ChangelogRoute,
  CompareRoute: CompareRoute,
  LearnRoute: LearnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
